name: smart_attendance
description: A Flutter app for smart attendance management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.3+1
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  connectivity_plus: ^6.0.3
  flutter_blue_plus: ^1.32.7
  image: ^4.1.7
  camera: ^0.10.5+5
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.3.10
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
